export {
  LazyAutomationSection,
  LazyContactsSection,
  LazyDashboardSection,
  LazyDeploymentsSection,
  LazyInfrastructureSectionView,
  LazyLogsSection,
  LazyMonitoringSection,
  LazyNotificationsSection,
  LazyPagesSection,
  LazyPlatformAdminsSection,
  LazyPlatformDashboardV2Section,
  LazyPlatformLogsSection,
  LazyPlatformSettingsSection,
  LazyProjectDetailSection,
  LazyPromisesSection,
  LazyReportsSection,
  LazySettingsSection,
  LazySitesSection,
  LazyUsersSection,
  DashboardDetailSection,
} from "./lazySections";
